### ISSUE TITLE
about data2

### ISSUE THREAD

**Issue by chengyu89527** [Linfeng-Tang/SeAFusion#13]
I check the google drive link , there are 3 file (image,label,visual) .which one is stand for infrared image. I find none of them is infrared

**Comment by Linfeng-Tang** [comment]
In fact, the images in the images folder contain four channels, namely three channels of visible images and a single channel of infrared images, and you need to separate them out. In addition, you can use the MSRS dataset (https://github.com/Linfeng-Tang/MSRS) to train and test SeAFusion.

**Comment by chengyu89527** [comment]
Thanks a lot, by the way, we need build log folder before braining and evalution

**Comment by chengyu89527** [comment]
also evalute.py gives :
Traceback (most recent call last):
  File "evaluate.py", line 191, in <module>
    evaluate()
  File "evaluate.py", line 165, in evaluate
    net.load_state_dict(torch.load(save_pth))
  File "/home/chengyu/anaconda3/envs/syn38/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BiSeNet:
	size mismatch for conv_out.conv_out.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 128, 1, 1]).
	size mismatch for conv_out16.conv_out.weight: copying a param with shape torch.Size([9, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([19, 64, 1, 1]).

**Comment by chengyu89527** [comment]
another issue is setup and restore model
/data/pcl/datasets/cityscapes/Fusion/val
Traceback (most recent call last):
  File "evaluate.py", line 191, in <module>
    evaluate()
  File "evaluate.py", line 172, in evaluate
    dsval = CityScapes(dspth, mode='val')
  File "/home/chengyu/SeAFusion-main/cityscapes.py", line 43, in __init__
    folders = os.listdir(impth)
FileNotFoundError: [Errno 2] No such file or directory: '/data/pcl/datasets/cityscapes/Fusion/val'
where I can find the the val dataset

**Comment by Linfeng-Tang** [comment]
In order to run evaluate. py successfully， you need to rewrite the dataloader according to how you store your datasets.

**Comment by chengyu89527** [comment]
thanks，I need generate some new fusion data&nbsp;


成大宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linfeng-Tang/SeAFusion] about data2 (Issue #13)





 
In order to run evaluate. py successfully， you need to rewrite the dataloader according to how you store your datasets.

**Comment by Linfeng-Tang** [comment]
We have updated evaluate.py and added the relevant data to run evaluate.py.
