### ISSUE TITLE
about train.py

### ISSUE THREAD

**Issue by HeHuasu** [Linfeng-Tang/SeAFusion#25]
您好，我现在想尝试复现训练过程，但是一直报错说缺少文件，请问这个文件是需要去官方下载还是要自己跑程序得到呢
Traceback (most recent call last):
  File "/root/autodl-nas/seafusion/train.py", line 398, in <module>
    setup_logger(logpath)
  File "/root/autodl-nas/seafusion/logger.py", line 20, in setup_logger
    logging.basicConfig(level=log_level, format=FORMAT, filename=logfile)
  File "/root/miniconda3/envs/venv/lib/python3.8/logging/__init__.py", line 1973, in basicConfig
    h = FileHandler(filename, mode)
  File "/root/miniconda3/envs/venv/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/root/miniconda3/envs/venv/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-nas/seafusion/logs/BiSeNet-2023-10-12-14-43-41.log'

**Comment by Linfeng-Tang** [comment]
你可以新建一个文件夹 或者在对应的地方使用os.makedirs( '/root/autodl-nas/seafusion/logs',
exist_ok=True )

HeHuasu ***@***.***> 于2023年10月12日周四 14:52写道：

**Comment by HeHuasu** [comment]
谢谢
