### ISSUE TITLE
无法进行后续语义分割训练

### ISSUE THREAD

**Issue by RicoVVV** [Linfeng-Tang/SeAFusion#46]
您好，我在完成融合训练后，尝试进行语义分割训练，但却总是报错难以找到目标文件夹，但是我确实是指定了正确的文件夹
|1 Fusion Image Sucessfully~!
/MSRS/Fusion/train/MSRS
Traceback (most recent call last):
  File "train.py", line 407, in <module>
    train_seg(i, logger, args)
  File "train.py", line 89, in train_seg
    ds = CityScapes('/MSRS/', cropsize=cropsize, mode='train', Method=Method)
  File "/home/zhangyuxinhd/SF2/cityscapes.py", line 43, in __init__
    folders = os.listdir(impth)
FileNotFoundError: [Errno 2] No such file or directory: '/MSRS/Fusion/train/MSRS'
我将分割的训练集指向了融合得到的训练图像，但依旧报错

**Comment by Linfeng-Tang** [comment]
尝试修改Dataloader 来解决这个问题。

RicoVVV ***@***.***> 于2024年5月30日周四 14:57写道：
