### ISSUE TITLE
about train_seg

### ISSUE THREAD

**Issue by Joanna006** [Linfeng-Tang/SeAFusion#49]
您好，在融合图像完成后，遇到的问题
|1 Fusion Image Sucessfully~!
./MSRS/Fusion/train
./MSRS/Fusion/train/MSRS
./MSRS/Label/train/MSRS
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    train_seg(i, logger, args)
  File "train.py", line 87, in train_seg
    ds = CityScapes('./MSRS/', cropsize=cropsize, mode='train', Method=Method)
  File "/root/autodl-tmp/SeAFusion-main/cityscapes.py", line 71, in __init__
    assert set(imgnames) == set(gtnames)
AssertionError

**Comment by Linfeng-Tang** [comment]
可以尝试一下修改Dataloader即可。

**Comment by wyfARTHUR** [comment]
您好，请问问题解决了吗？具体是如何修改的？
